<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>94b94131-d4c1-46d6-a216-264182ff3eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.slp-btn.navigation-item-top.slp-ml-24.slp-btn-ghost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be-navigation-desktop']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e36dc86-1b29-4466-bf64-986ee14f7ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gitlab.com/users/sign_in/</value>
      <webElementGuid>94a0b626-6cf1-48d6-a903-c2627b168d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e82069af-fdfd-4a89-9611-4d0e2190431d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>3beda41c-ade2-463a-ae74-d3bf0daab617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slp-btn navigation-item-top slp-ml-24 slp-btn-ghost</value>
      <webElementGuid>d04088a2-29d0-413d-b2a5-f2f37648dc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>2ea0dee5-5525-40a9-a8ca-3f3e0c635321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be-navigation-desktop&quot;)/div[@class=&quot;navigation&quot;]/div[@class=&quot;navigation-top&quot;]/a[@class=&quot;slp-btn navigation-item-top slp-ml-24 slp-btn-ghost&quot;]</value>
      <webElementGuid>72dcb2c2-4414-49a7-be6b-cdbfa6c2c3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='be-navigation-desktop']/div/div/a</value>
      <webElementGuid>26176d7e-2961-4d93-a6af-fe4130eaf1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>c40e9ac1-e5b3-49f9-abb0-1c4095ac8f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/following::a[1]</value>
      <webElementGuid>80a1b413-4961-4968-942b-ea0229831661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set up support services'])[1]/following::a[2]</value>
      <webElementGuid>77a5c87a-1353-4fbe-84ba-13c14815bd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>345bd49e-e308-4eac-aafe-ed663366a5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/preceding::a[1]</value>
      <webElementGuid>fcbd6a4c-15a9-40e1-a66e-e67cadd58456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>b6408d21-426a-4ed3-8476-a65cfacd099c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gitlab.com/users/sign_in/')]</value>
      <webElementGuid>f934a9f0-5f60-4370-8809-19e7cf0ef4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>143aebb9-101c-4abb-8974-01b4ca31eae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gitlab.com/users/sign_in/' and @title = 'Login' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>1d3167d4-aec2-45c1-9b38-7671e8405ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
