<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>789caee2-38db-4045-ac53-eeb4c394f43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.slp-btn.navigation-item-top.slp-mr-24.slp-btn-ghost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be-navigation-desktop']/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09242ec5-3674-4191-9b04-2d277d691187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gitlab.com/users/sign_up/</value>
      <webElementGuid>b0605967-2c34-43b0-8c31-1ecd6e986473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>b64f352b-17b4-45e6-b5cf-0a393e67c536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>5fe9d31d-9420-49ad-82f6-56d85f8a5add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slp-btn navigation-item-top slp-mr-24 slp-btn-ghost</value>
      <webElementGuid>a9d5275a-01d7-4f7c-b905-3fc4f96cf235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register </value>
      <webElementGuid>e0afffce-ce68-4734-8ba7-26529345f5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be-navigation-desktop&quot;)/div[@class=&quot;navigation&quot;]/div[@class=&quot;navigation-top&quot;]/a[@class=&quot;slp-btn navigation-item-top slp-mr-24 slp-btn-ghost&quot;]</value>
      <webElementGuid>4446a8f8-ae7c-4719-bffd-063b8c918881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='be-navigation-desktop']/div/div/a[2]</value>
      <webElementGuid>70159a60-d9dd-4d94-9a68-89c70bb2f0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>c833f38e-c5da-4b9d-a4a1-48740fa7535b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::a[1]</value>
      <webElementGuid>b6135719-8b4f-4c1f-a100-0170fabd3d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>b20fcf3b-4784-42d1-8ad7-1cc09335ba00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why GitLab'])[1]/preceding::a[2]</value>
      <webElementGuid>041ee597-2427-45ea-b97f-7f8b3a8c04c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[1]/preceding::a[2]</value>
      <webElementGuid>5e72dd93-44db-40ab-a149-6acf0bd3ff50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>1121a0cb-af70-46a5-9063-ae8d2831c700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gitlab.com/users/sign_up/')]</value>
      <webElementGuid>1e5788b9-ae82-4600-8c32-83118af18081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>268e0d6f-dc17-48b0-ad75-5dcf6bb3883f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gitlab.com/users/sign_up/' and @title = 'Register' and (text() = ' Register ' or . = ' Register ')]</value>
      <webElementGuid>721a166a-7a4c-4b53-912a-3ce816e25d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
