<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log In_shopee-searchbar-input__input</name>
   <tag></tag>
   <elementGuidId>d3c463a8-bc96-4712-ad7e-1de08a217caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.shopee-searchbar-input__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa05fe43-f030-42b7-87fe-7acfa76af9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>terrypalmerid Diskon s/d 60%</value>
      <webElementGuid>b19511fa-0bec-4d5a-bf9a-17d837afa795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopee-searchbar-input__input</value>
      <webElementGuid>ad60f1fc-d8d4-4454-bd75-5d6fbee3bc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>4972a361-33ec-4755-a0cb-b85d6f3f51c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>terrypalmerid Diskon s/d 60%</value>
      <webElementGuid>0d74ddf0-c528-4a70-af22-0062c47a789d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1c2ff9c9-6b52-4898-9a56-b8463efd2a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>3d7712d6-854e-4e4b-ac9c-a6c149576e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>shopee-searchbar-listbox</value>
      <webElementGuid>b0b65aa0-98f6-4437-b615-c01d2aae37ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;shopee-top shopee-top--sticky&quot;]/div[@class=&quot;container-wrapper header-with-search-wrapper&quot;]/div[@class=&quot;container header-with-search&quot;]/div[@class=&quot;header-with-search__search-section&quot;]/div[@class=&quot;shopee-searchbar shopee-searchbar--focus&quot;]/div[@class=&quot;shopee-searchbar__main&quot;]/form[@class=&quot;shopee-searchbar-input&quot;]/input[@class=&quot;shopee-searchbar-input__input&quot;]</value>
      <webElementGuid>10aa7474-8466-4abf-80fd-5dc7131e14fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>3c4e4e8d-7614-4d5b-bedf-bb7273aaa89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[2]/div/div/div/div/form/input</value>
      <webElementGuid>93384bd0-484b-4fdd-84f7-6bef4b230579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d76a32fb-ca00-42e8-8d61-ed4d779acea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'terrypalmerid Diskon s/d 60%']</value>
      <webElementGuid>b4913480-b41e-4f42-96e9-44d623a866be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
